<?php

namespace SysTech\TestTaskBundle\Entity\Db2\Repository;

/**
 * SkuStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkuStockRepository extends \Doctrine\ORM\EntityRepository
{
}
