<?php

namespace SysTech\TestTaskBundle\Entity\Db1\Repository;

/**
 * SkuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkuRepository extends \Doctrine\ORM\EntityRepository
{
}
