<?php

namespace SysTech\TestTaskBundle\Repository\Db1;

/**
 * SkudsadasdasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkudsadasdasRepository extends \Doctrine\ORM\EntityRepository
{
}
