<?php

namespace SysTech\TestTaskBundle\Repository\Db1;

/**
 * SkusdfghRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkusdfghRepository extends \Doctrine\ORM\EntityRepository
{
}
