<?php

namespace SysTech\TestTaskBundle\Repository\Db1;

/**
 * TableRelationsdfghjklRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableRelationsdfghjklRepository extends \Doctrine\ORM\EntityRepository
{
}
