<?php

namespace SysTech\TestTaskBundle\Repository;

/**
 * TableRelationsdfghjklghjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableRelationsdfghjklghjRepository extends \Doctrine\ORM\EntityRepository
{
}
